### ISSUE TITLE
format numbers to 3 decimal places

### ISSUE THREAD

**Issue by pete911** [nom1/exercise#4]
Format to two decilam places

```
x = 3.1415926
print("Formatted x: {0:.2f}".format(x))
```

`{0:.2f}` - is placeholder, where the first number before colon `:` says what argument from `.format` function should be substituted (in this case, there is only one - x). After colon `:` we have number of decinal places to display `.2` and the typ of number `f`, which is float.

**Comment by nom1** [comment]
which file do you want me to edit for this one

**Comment by nom1** [comment]
i understand what it means but what should i do with it

**Comment by pete911** [comment]
Play with it, understand it, search for different options ... When I get home I'll show you

**Comment by nom1** [comment]
hello

**Comment by nom1** [comment]
I am in it class do you want me to send you ze code

**Comment by pete911** [comment]
what's up? why are you still at school?

**Comment by nom1** [comment]
I have gcse it

**Comment by pete911** [comment]
ok, just create a file here and put it there, we'll go through it when I get home, I am at work, cannot talk too much, have work to do

**Comment by nom1** [comment]
righty oo

**Comment by nom1** [comment]
how do you create a file

**Comment by pete911** [comment]
Send it via email, I'll show you at home

**Comment by nom1** [comment]
I sent it, good riddance :)

**Comment by nom1** [comment]
see you at home I am leaving
